server.port=8084

management.endpoints.web.exposure.include=prometheus
management.endpoint.prometheus.access=unrestricted
management.prometheus.metrics.export.enabled=true

# expose same path name: /metrics
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.prometheus=metrics