global:
    scrape_interval: 2s
    evaluation_interval: 2s

scrape_configs:
    - job_name: "go-gin"
      static_configs:
          #   - targets: ["host.docker.internal:8081"]
          - targets: ["54.179.157.206:8081"]

    - job_name: "js-express"
      static_configs:
          #   - targets: ["host.docker.internal:8082"]
          - targets: ["13.212.74.107:8082"]

    - job_name: "csharp-api"
      static_configs:
          # - targets: ["host.docker.internal:8083"]
          - targets: ["52.77.210.38:8083"]

    - job_name: "java-api"
      static_configs:
          # - targets: ["host.docker.internal:8084"]
          - targets: ["13.212.236.217:8084"]

    - job_name: "rust-api"
      static_configs:
          #       - targets: ["host.docker.internal:8085"]
          - targets: ["13.212.187.248:8085"]
